format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_spi}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_SPI_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_spi, value: Asynchronous}
  - type: Boolean
    attributes: {id: DRV_SPI_SYS_DMA_CODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_spi, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_SPI_SYS_DMA_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_spi, value: 'false'}
  - type: Integer
    attributes: {id: DRV_SPI_SYS_DMA_ENABLE_CNTR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_spi, value: '0'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_spi}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_SPI_MODE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: Asynchronous}
      - type: String
        attributes: {id: DRV_SPI_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: FLEXCOM4}
      - type: Integer
        attributes: {id: DRV_SPI_RX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: '-1'}
      - type: Integer
        attributes: {id: DRV_SPI_TX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: '-1'}
      - type: Boolean
        attributes: {id: DRV_SPI_TX_RX_DMA}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: 'false'}
      - type: Boolean
        attributes: {id: DRV_SPI_TX_RX_DMA_EN}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: 'false'}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: drv_spi}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: drvWifiWinc}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: spi}
      - type: DirectDependency
        attributes: {id: drv_spi_SPI_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: flexcom4}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: FLEXCOM4_SPI}
- type: ElementPosition
  attributes: {x: '348', y: '149', id: drv_spi}
